steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/pmmlserver:1.0', '.' ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pmmlserver:1.0']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'pmmlserver', '--image', 'gcr.io/$PROJECT_ID/pmmlserver:1.0',
         '--port', '5000', '--region', 'us-east4', '--platform', 'managed', "--allow-unauthenticated"]
images:
- 'gcr.io/$PROJECT_ID/pmmlserver:1.0'